routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return view('app.welcome');
});

Auth::routes();

Route::group(['middleware' => ['web', 'auth']], function() {
    Route::get('/home', 'HomeController@index');
});


// Admin routes

Route::group(['prefix' => 'admin'], function() {
    Route::get('register', 'Admin\Auth\RegisterController@showRegistrationForm');
    Route::post('register', 'Admin\Auth\RegisterController@register');
    Route::get('login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('login', 'Admin\Auth\LoginController@login')->name('admin.login');
    Route::post('logout', 'Admin\Auth\LoginController@logout')->name('admin.logout');

    // Admin auth routes
    Route::group(['middleware' => ['web', 'auth.admin']], function() {
        Route::get('dashboard', function() {
            return view('admin.dashboard');
        })->name('admin.dashboard');

        // User routes
        Route::group(['middleware'=> 'can:handle,App\Models\User'], function() {
            Route::get('/users', 'Admin\UserController@index')->name('admin.users.index');
            Route::get('users/search', 'Admin\UserController@search')->name('admin.users.search');
            Route::get('users/{user}', 'Admin\UserController@get')->name('admin.user.get');
            Route::post('users/update/{user}', 'Admin\UserController@update')->name('admin.user.update');
            Route::post('users/avatar/store/{user}', 'Admin\UserAvatarController@store')->name('admin.user.avatar.store');
        });

        // TODO badge policy
        // Badges
        Route::get('/badges', 'Admin\BadgeController@index')->name('admin.badges.index');
    });

});

app/Models/Badge.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Badge extends Model
{
    protected $guarded = [];

    public function badgeCategory()
    {
        return $this->belongsTo(BadgeCategory::class);
    }

    public function teams()
    {
        return $this->belongsToMany(Team::class);
    }

    public function getImageAttribute($value)
    {
        return new Image($value, 'badges/');
    }

    public function scopeActive($query){
        return $query->where('is_active', 1);
    }
}

app/Http/Controllers/Admin/BadgeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Badge;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BadgeController extends Controller
{
    public function index(){
        $badges = Badge::active()->paginate(100);

        return view('admin.badges.index', compact('badges'));
    }
}

resources/views/admin/badges/index.blade.php
@extends('admin.layout')

@section('content')
    <div class="container is-fluid">
        {{--<form method="get" action="{{ route('admin.users.search') }}" >
            {{ csrf_field() }}
            <div class="control is-horizontal has-text-centered">
                <p class="control has-addons-right">
                    <input type="text" class="input" name="q" placeholder="Név, felhaszánlónév, email">
                </p>
                <button class="button is-primary">
                    <span class="icon">
                        <i class="fa fa-search"></i>
                    </span>
                    <span>Keresés</span>
                </button>
            </div>
        </form>--}}

        <table class="table is-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>Kép</th>
                <th>Név</th>
                <th>Kategória</th>
            </tr>
            </thead>
            <tbody>
            @foreach($badges as $badge)
                <tr>
                    <td>{{ $badge->id }}</td>
                    <td><img src="{{ $badge->image->squareSmall()->getUrl() }}"></td>
                    <td><a href="#">{{ $badge->name }}</a></td>
                    <td>{{ $badge->badgeCategory->display_name }}</td>
                    <td>{{-- *$user->teams --}}</td>
                    <td>
                        <a href="#" class="button is-success">
                            <span class="icon"><i class="fa fa-edit"></i></span>
                        </a>
                        <i class="button is-danger is-outlined">
                            <span class="icon"><fa class="fa fa-times"></fa></span>
                        </i>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $badges->links() }}
    </div>
@endsection